### ISSUE TITLE
Segfault with latest Rakudo

### ISSUE THREAD

**Issue by evanmiller** [scmorrison/uzu#11]
Likely a bug in Rakudo, but I wanted to make you aware of memory errors when testing Uzu with the latest Rakudo. I've filed a bug against Rakudo here: https://rt.perl.org/Ticket/Display.html?id=131889

**Comment by scmorrison** [comment]
Thanks, there is a discussion on p6 multithreading here as well https://stackoverflow.com/questions/43449883/how-many-promises-can-perl-6-keep/43452246

**Comment by scmorrison** [comment]
I am backing out of the promises for now. It left everything too unstable. A new issue that was introduced is the watch dev server would just hang after a few re-renders. Fortunately they are putting a lot of effort into these features. So hopefully we will have something more reliable soon.

**Comment by evanmiller** [comment]
That's fine with me. Someone in IRC suggested using `.hyper.map` to get parallelism without using promises.
