### ISSUE TITLE
uzu init should support Mustache

### ISSUE THREAD

**Issue by evanmiller** [scmorrison/uzu#14]
Right now `uzu init` creates a project with `.tt` files. There should be an option to create .mustache files instead (and of course set `template_engine` appropriately in config.yml).

**Comment by scmorrison** [comment]
Thanks for capturing this. I have been planning on making mustache the default and adding an option for init to select the template. init needs to be a little smarter in how it handles user input as well.

**Comment by scmorrison** [comment]
`uzu init` now asks for template engine: `mustache` or `tt`.

thanks,
sam
