### ISSUE TITLE
Themed partials

### ISSUE THREAD

**Issue by evanmiller** [scmorrison/uzu#17]
I have a project with HTML content that I need to render in two very different contexts:

* For a website
* As an Apple Help book

Apple Help books are directories of HTML files, but have peculiar formatting and linking rules, so I really would like a separate set of partial templates. I was thinking maybe each context use the "theme" feature and override the default partials. E.g.

```
|-- partials
  |-- article_header.mustache
  |-- article_footer.mustache
|-- themes
  |-- default
    |-- layout.mustache
  |-- helpbook
    |-- partials
      |-- article_header.mustache
      |-- article_footer.mustache
    |-- layout.mustache
```

Would that be an appropriate extension of themes?

Relatedly, I would also need separate URL constructors for the two themes. E.g. a URL in the default theme might look like `/help/compute/about_indicator.html`, but for the helpbook it needs to be `help:anchor=Wizard_compute_about_indicator bookID=org.evanmiller.wizard.help`. We can have a separate discussion about URL construction, but I wanted to give you more context about the problem.

**Comment by scmorrison** [comment]
Would creating new partials in the normal `partials/` directory and including those in your helpbook layout work?

```
|-- partials
  |-- article_header.mustache
  |-- article_footer.mustache
  |-- ahb_header.mustache
  |-- ahb_footer.mustache
|-- themes
  |-- default
    |-- layout.mustache
  |-- helpbook
    |-- layout.mustache
```

Also, I will add an option like `uzu --layout helpbook build` for specifying a target theme to use. It would probably be useful to expose the current `theme` and `page_name` to the templates as well.

**Comment by evanmiller** [comment]
Hi, I think I need parallel partials. A typical article looks like this:

```
---
title: About indicator variables
---
{{> article_header }}
<p>Lorem ipsum dolor...</p>
{{> article_footer }}
```

Unless you're suggesting I move `{{> article_header }}` and `{{> article_footer }}` over to the layout file? I suppose that could work; I've usually just thought of the layout file as providing the very basics though.

**Comment by scmorrison** [comment]
ok, how about something like this. uzu already supports nested partial folders:

```
|-- partials
  |-- article_header.mustache
  |-- handbook
    |-- article_header.mustache
```

I can expose a new variable for the current theme and you could use something like this in the mustache templates:

```mustache
{{#theme_default}}
{{> article_header }}
{{/theme_default}}
{{#theme_handbook}}
{{> handbook/article_header }}
{{/theme_handbook}}
```

Do you think something like that would work for your use case?

**Comment by evanmiller** [comment]
The example you give results in considerably more code than just allowing partials in the themes directory. I'm not sure I understand what the harm is, since there's already a layout template in there.

**Comment by scmorrison** [comment]
No harm, and actually, now that I think about it, it would be worth supporting as it will also make themes more portable. Ok, give me a couple of days and I will see what I can come up with.

**Comment by evanmiller** [comment]
Thanks!

**Comment by scmorrison** [comment]
Hi @evanmiller, I have added initial support for theme partials. Theme partials override the top-level partials if they share the same file name.

**Comment by evanmiller** [comment]
Excellent! I won't be using the feature immediately but I'll open a new issue if I encounter any problems.

By the way, I've found that removing `.perl6/precomp` solved some problems I had with updated versions of Uzu not seeming to be installed. Might add a note to the README next to the tip about removing `.zef/store/uzu.git` etc.

**Comment by scmorrison** [comment]
thanks for the tip. I will add it to troubleshooting.
