### ISSUE TITLE
Feature request: Per-page config

### ISSUE THREAD

**Issue by evanmiller** [scmorrison/uzu#2]
I'm interested in using uzu as a poor man's CMS. Basically I have a site with a number of long-ish articles, and I want to make a separate page for each article. I'd like to have additional metadata associated with each article, e.g. related links, timestamp, title, etc. I envision a file layout like:

```
pages
 |-- article1.tt
 |-- article2.tt
i18n
 |-- en.yml
 |-- en
    |-- article1.yml
    |-- article2.yml
```

Uzu would collate the config files, basically merging article1.yml and en.yml when generating article1, etc. Does that make sense? Does it fit with your vision or should I look elsewhere?

**Comment by scmorrison** [comment]
Hi @evanmiller 

This is along the lines of what I was thinking. I am planning on adding support for nested folder posts as well. Maybe something like this?

```
pages
 |-- article1.tt
 |-- article2.tt
 |-- blog           # arbitrary folder structure
    |-- 20170715                         # /blog/20170715/
        |-- article3.tt                  # /blog/20170715/article3.html
    |-- 2017 # /blog/2017/
        |-- 07                           # /blog/2017/07/
            |-- 16                       # /blog/2017/07/16/
                 |-- article4.tt         # /blog/2017/07/16/article4.html
 |-- categories     # arbitrary folder structure
    |-- travel                           # /categories/travel/
        |-- fiji.tt                      # /categories/travel/fiji.html
i18n
 |-- en.yml    # language globals (en)
 |-- ja.yml    # language globals (ja)
 |-- en
     |-- article1.yml  # article specific variables
     |-- article2.yml
 |-- ja
     |-- article1.yml  # article specific variables
     |-- article2.yml
 |-- blog              # map to pages structure
     |-- 20170715
         |-- en
             |-- article3.yml  # article specific variables (en)
         |-- ja
             |-- article3.yml  # article specific variables (ja)
     |-- 2017
         |-- 07
             |-- 16
                 |-- en
                     |-- article4.yml  # article specific variables (en)
                 |-- ja
                     |-- article4.yml  # article specific variables (ja)
 |-- categories
     |-- travel
         |-- en
             |-- fiji.yml  # article specific variables (en)
         |-- ja
             |-- fiji.yml  # article specific variables (ja)
```

Sam

**Comment by evanmiller** [comment]
Cool, nested folder posts sound great. I don't really need i18n myself, so maybe consider a structure like:

```
i18n
 |-- en.yml    # language globals (en)
 |-- ja.yml    # language globals (ja)
 |-- article1.yml # article variables
 |-- article1
     |-- en.yml  # article1 lang specific variables
     |-- ja.yml
 |-- article2.yml # no i18n on this article
 |-- article3.yml
 |-- article3.en.yml  # alternate method for lang specific variables
 |-- article3.ja.yml
```

**Comment by scmorrison** [comment]
After staring at all of this I am trying to decide which of these approaches would be the most painless for the users.

I think I like this the most so far:

```
i18n
 |-- en.yml    # language globals (en)
 |-- ja.yml    # language globals (ja)
 |-- article1
     |-- en.yml  # article1 lang specific variables
     |-- ja.yml
 |-- categories
     |-- travel
         |-- fiji
             |-- en.yml  # article specific variables (en)
             |-- ja.yml  # article specific variables (ja)
```

I think that the scenario where i18n isn't needed then the default language could be used.

I do like the aesthetics of the `article3.en.yml`, but it might get long if there is a long file names. I think the folder-name-as-article might be the way to go is that it also makes it easier to rename paths / articles. We would only have to rename the `pages` yml file and the single `i18n` folder. Instead of `our-first-time-scuba-diving.en.yml` and the other languages if they exist, `our-first-time-scuba-diving.ja.yml`, `our-first-time-scuba-diving.es.yml`:

```
 |-- categories
     |-- travel
         |-- our-first-time-scuba-diving.en.yml  # article specific variables (en)
         |-- our-first-time-scuba-diving.ja.yml  # article specific variables (ja)
```

Also, folder-name-as-article would reduce duplication:

```
 |-- article1
     |-- en.yml  # article1 lang specific variables
     |-- ja.yml
 |-- categories
     |-- travel
         |-- our-first-time-scuba-diving
             |-- en.yml  # article specific variables (en)
             |-- ja.yml  # article specific variables (ja)
```

For a project with a single language, say `en`, we could have this:

```
pages
 |-- article1.tt
 |-- article2.tt
 |-- blog  
    |-- 20170715                         # /[en|ja]/blog/20170715/
        |-- article3.tt                  # /[en|ja]/blog/20170715/article3.html
    |-- 2017 # /blog/2017/
        |-- 07                           # /[en|ja]/blog/2017/07/
            |-- 16                       # /[en|ja]/blog/2017/07/16/
                 |-- article4.tt         # /[en|ja]/blog/2017/07/16/article4.html
 |-- categories
    |-- travel                           # /[en|ja]/categories/travel/
        |-- fiji.tt                      # /[en|ja]/categories/travel/fiji.html
i18n
 |-- en.yml    # language globals (en)
 |-- ja.yml    # language globals (ja)
 |-- article1
     |-- en.yml
 |-- article2
     |-- en.yml
 |-- blog
     |-- 20170715
         |-- article3
             |-- en.yml
     |-- 2017
         |-- 07
             |-- 16
                 |-- article4
                     |-- en.yml
 |-- categories
     |-- travel
         |-- fiji
             |-- en.yml
```

Also, if the config lists more than one language, say `en`, `ja`, `es`, but only one i18n file exists `es`, then we will use that language file for all languages for that article.

```
# config.yml
language:
    - en
    - es
    - ja

# i18n
 |-- blog
     |-- 2017
         |-- 07
             |-- 16
                 |-- article4
                     |-- es.yml

/blog/2017/07/16/article4.html     # using es file
/es/blog/2017/07/16/article4.html  # using es file
/ja/blog/2017/07/16/article4.html  # using es file
```

**Comment by evanmiller** [comment]
Cool. The folder structure is certainly easier to rename than `article1.en.yml`, `article2.ja.yml`, etc.

In my own case, if I were to do i18n, I think I'd want localized templates too.  (I.e. the article text would be localized also.) So I'd want the top-level folders to be "pages" and "vars" or something like that.

```
|-- pages
  |-- article1
    |-- en.tt
  |-- article2
    |-- en.tt
|-- vars
  |-- article1
    |-- en.yml
  |-- article2
    |-- en.yml
```

But then at that point I might want the language up top:

```
|-- config.yml
|-- en
   |-- pages
     |-- article1.tt
     |-- article2.tt
   |-- vars
     |-- article1.tt
     |-- article2.tt
```

Not sure what the right answer is here!

**Comment by scmorrison** [comment]
Instead of having a generic vars folder, how about supporting page-centric vars in the page template files themselves and make a distinction between variable scope: `site`, `page`, and `i18n`.

A single page could look something like this (only a rough idea at the moment):

```
---
title: Vacation to Fiji
date: 2017-07-17
author: Arnold Schwarzenegger
tags: ['travel', 'fiji', 'vacation']
---
<div>
    Title: [% page.title %]<br/>
    Author: [% page.author %]<br/>
    Date: [% page.date %]<br/>

    <!-- when using i18n vars -->
    <p>[% i18n.body %]</p>

    <!-- without i18n vars -->
    <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. </p>

    <!-- when using i18n vars -->
    [% for tag in i18n.tags %]
       <li>[% tag %]</li>
    [% end %]

    <!-- without i18n vars -->
    [% for tag in page.tags %]
       <li>[% tag %]</li>
    [% end %]
 </div>
```

A template file cool look like this:

```
<head>
    <title>[% page.title %] - [% site.title %]</title>
</head>
<body>
```

`site` variables would be defined in `config.yml`, `page` variables defined in the pages themselves, and `i18n` variables defined in the `i18n` folder structure:

```
i18n
 |-- en.yml    # language globals (en)
 |-- ja.yml    # language globals (ja)
 |-- article1
     |-- en.yml
 |-- article2
     |-- en.yml
 |-- blog
     |-- 20170715
         |-- article3
             |-- en.yml
     |-- 2017
         |-- 07
             |-- 16
                 |-- article4
                     |-- en.yml
 |-- categories
     |-- travel
         |-- fiji
             |-- en.yml
```

If we nest the variables under their scope level then it will make it easier to determine which variables we want to use where and we wouldn't have to worry about precedence (none of this: page vars override i18n vars override site vars).

A few related ideas. I plan on adding support for other templating engines (mustache). Second, I like the idea of creating dynamic variables for different use cases. For example, pagination, tag clouds, dynamically generated category list pages, tag list pages, etc. and I think if we can put some meta data into the page (similar to what you were alluding to in regards to page-specific (i18n neutral) it could open up options for dynamically generating navigational / support components for the rendered site.

At the same time I want to make each feature as simple as possible to use. If we do go with page-embedded variables, then I want to use the same format across all templating engines.

**Comment by evanmiller** [comment]
I like the page-embedded variables!

One other related request I'd have is a natural way to write articles in Markdown -- maybe this could be a special page variable or something e.g.

```
title: My Vacation
author: Arnie
markup: markdown
--
Great trip! *Hasta la vista, baby!*
```

**Comment by scmorrison** [comment]
Ok, I have added the `i18n.varaiblename` and `site.variablename` functionality. The old variables will still work without the scope for now. For the page variables, Template6 has this built in so I have added an example in the [README#page-variables](https://github.com/scmorrison/uzu#page-variables). This will work without the `page.` scope prefix, which makes sense considering it is already local.

[Template::Mustache](https://github.com/softmoth/p6-Template-Mustache) doesn't support page-level variable setting, but we can add in the yaml variables support relatively easily.

I have also added a note for the `site.` and `i18n.` variable prefix usage in the README.

Next I will start working on the nested `i18n` variables, but I think using the current `tt` [page variables](https://github.com/scmorrison/uzu#page-variables). should work for your current needs. 

I like the idea of supporting Markdown templates too. After the nested `i18n` variable support, Mustache support, I will start looking into Markdown. https://github.com/scmorrison/uzu/projects

**Comment by scmorrison** [comment]
Just wanted to update on the progress. I have added Mustache support and yaml page-variables for both Template6 and Mustache templates.

You can now add something like this at the top of your page templates:

`pages/index.tt`

```html
---
title: Welcome to my site
---
<div>My index page</div>
```

Then you can access the page variables from other templates / partials (Template6):

`partials/head.tt`
```html
<head>
    <meta charset="utf-8">
        <title>[% title %] - [% i18n.site_name %]</title>
        <meta name="description" content="">
    ...
```

...or for Mustache:


`partials/head.mustache`
```html
<head>
    <meta charset="utf-8">
        <title>{{ title }} - {{ i18n.site_name }}</title>
        <meta name="description" content="">
    ...
```

Page variables can be accessed from any template (pages, partials, and layouts). Hope this is useful.

To use the yaml variable block in Template6 you will need to uninstall Template6:

```
zef uninstall Template6
rm -rf ~/.zef/store/template6.git ~/.zef/tmp/template6.git
zef install Template6
```

If needed, you can do a full uzu reinstall:
```
zef uninstall Uzu
rm -rf ~/.zef/store/uzu.git ~/.zef/tmp/uzu.git
zef install Uzu
```

Thanks,
Sam

**Comment by evanmiller** [comment]
Thanks. I tried reinstalling Uzu, but the HTTP::Server::Async dependency failed to pass the test suite. I have filed an issue about that here:

https://github.com/perl6/perl6-http-server-async/issues/32

**Comment by scmorrison** [comment]
Thanks, you can also try installing that module without the tests:

```
zef install HTTP::Server::Async --/test
```

Not sure if this will make a difference, but I am able to install `HTTP::Server::Async` with perl6  2017.06-01 and zef  0.1.21 without disabling tests.

**Comment by evanmiller** [comment]
The HTTP::Server::Async issue was OS X-specific and is now resolved.

I'm now getting a dependency failure for File::Temp. I have filed an issue here: https://github.com/perlpilot/p6-File-Temp/issues/23
