### ISSUE TITLE
Disable layout on a per-page basis

### ISSUE THREAD

**Issue by evanmiller** [scmorrison/uzu#25]
I have a project where one file needs to be XHTML, and all other HTML (all built files need to have extension  `.html` though). I'd like to be able to disable the layout for the one XHTML page.

**Comment by scmorrison** [comment]
Hi @evanmiller, you can now create a `nolayout` variable in page yaml and the page will render without the layout.

```
---
nolayout: true
```

The value can be anything, the variable just needs to be defined.

**Comment by evanmiller** [comment]
Works great, thanks!
