### ISSUE TITLE
Variables don't propagate to embedded partials

### ISSUE THREAD

**Issue by evanmiller** [scmorrison/uzu#29]
pages/index.mustache:
```
---
hello: "Hello!"
---
{{> partial1 }}
```

partials/partial1:
```
{{> partial2 }}
```

partials/partial2:
```
{{ hello }}
```

Expected output: build/index.html contains "Hello!"

Actual output: build/index.html is empty

**Comment by scmorrison** [comment]
ok, this should work as expected now. also added coverage for embedded partials.
