### ISSUE TITLE
Uzu attempts to compile Vim swap files (e.g. .index.tt.swp)

### ISSUE THREAD

**Issue by evanmiller** [scmorrison/uzu#3]
If I attempt to build a project while editing a template in Vim, I get an error like:

```
Malformed UTF-8 at line 1 col 17
  in sub build at /Users/emiller/Code/rakudo/install/share/perl6/site/sources/09A80BAF814E9ED57510ACEA7ABD2E08BA63E4B6 (Uzu::Render) line 249
  in sub MAIN at /Users/emiller/Code/rakudo/install/share/perl6/site/sources/28DAFFBFC13CA36F7054D7A42E9F7D0EAB85E83F (Uzu::CLI) line 38
  in block <unit> at /Users/emiller/Code/rakudo/install/share/perl6/site/resources/BEF8B0D598CE2C8868AC1830A48C46EB8DE3DEA5 line 5
  in sub MAIN at /Users/emiller/Code/rakudo/install/share/perl6/site/bin/uzu line 2
  in block <unit> at /Users/emiller/Code/rakudo/install/share/perl6/site/bin/uzu line 2
```

The regex [passed](https://github.com/scmorrison/uzu/blob/master/lib/Uzu/Render.pm6#L15) to "find" should exclude dot-files, or .swp/.swo files, or both.

**Comment by scmorrison** [comment]
Hi @evanmiller, the regex is only looking for files with the extensions `<tt mustache>`, but I will double check. Delete the swap file and see if you still get the error. If so then the error might also be because some files are missing in the project folder. This is part of a larger issue that I am working on resolving at the moment. Can you make sure your project has at least these files:

```
├── config.yml
├── pages
│   └── index.tt
├── partials
├── public
├── i18n
│   ├── en.yml
└── themes
    └── default
        ├── assets
        └── layout.tt
```

thanks, sam

**Comment by evanmiller** [comment]
The error disappears when I close Vim (i.e. delete the swap file). I think the regex needs a $ at the end.

**Comment by scmorrison** [comment]
I have updated master with the missing $. I use vim myself and haven't run into that error you were seeing, but regardless, thanks for catching it.

You can reinstall using these steps to ensure you get the latest code:

```
zef uninstall Uzu
rm -rf ~/.zef/store/uzu.git ~/.zef/tmp/uzu.git
zef install Uzu
```

**Comment by evanmiller** [comment]
Still failing. I think the pipe character in the regex is being evaluated as "or" rather than a unary operator applied to $exts -- so the regex matches anything containing a period.

**Comment by scmorrison** [comment]
ok, so... this should be working correctly now... thanks again for catching that. I think I was originally using the `|` because I was expanding a hash into parameters somewhere and .... well. it must have been late.

**Comment by evanmiller** [comment]
Works, thanks!
