### ISSUE TITLE
Deeply embedded partials expand to nothing

### ISSUE THREAD

**Issue by evanmiller** [scmorrison/uzu#31]
pages/index.mustache:

```
---
hello: "Hello!"
something:
  - g: d
---
{{> partial1 }}
```

partials/partial1.mustache:
```
{{> partial2 }}
```

partials/partial2.mustache:
```
{{#something}}
<partial2>{{> partial3 }}</partial2>
{{/something}}
```

partials/partial3.mustache:
```
<partial3>{{ hello }}</partial3>
```

Expected output: `<partial2><partial3>Hello!</partial3></partial2>`

Actual output: `<partial2></partial2>`

**Comment by scmorrison** [comment]
Hi @evanmiller, a first pass at this has been added. Variables will propagate from the page and every parent partial into the deepest partials.

**Comment by evanmiller** [comment]
Thanks. The partials are expanding now, but the variables are behaving unexpectedly.

pages/about_indicator.mustache:
```
---
title: About indicator variables
see_also_pages:
  - page: compute/create_indicator
  - page: compute/edit_indicator
  - page: compute/about_recode
  - page: overview/about_models
---
{{> see_also }}
```

partials/see_also.mustache:
```
<ul>
{{#see_also_pages}}
<li> {{> link }} </li>
{{/see_also_pages}}
</ul>
```

partials/link.mustache:
```
{{ title }}
```

Expected output:
```
<ul>
<li> Creating an indicator variable </li>
<li> Editing an indicator variable </li>
<li> About recode variables </li>
<li> About models </li>
</ul>
```

Actual output:
```
<ul>
<li> About indicator variables </li>
<li> About indicator variables </li>
<li> About indicator variables </li>
<li> About indicator variables </li>
</ul>
```

**Comment by scmorrison** [comment]
ok, so... this is a tricky one. There is currently no way to pass these loop iteration variables to the child template. So what you are seeing is the child template picking up the `page` `title` variable.

For example, if you do this:

pages/about_indicator.mustache:

```
---
title: About indicator variables
see_also_pages:
  - page: compute/create_indicator
  - page: compute/edit_indicator
  - page: compute/about_recode
  - page: overview/about_models
---
{{> see_also }}
```
partials/see_also.mustache:

```
<ul>
{{> link }}
</ul>
```

partials/link.mustache:

```
{{#see_also_pages}}
<li> {{ title }} </li>
{{/see_also_pages}}
```

Then the `see_also_pages` has will be correctly propagated. Each partial is rendered independently and imported into its parent. This is because we support partial-specific variables that need to apply to the partial alone before its parent's own variables are rendered. The variables available inside of the `see_also_pages` loop are not passed around during rendering to the child partial. This is loop piece is handled by Template::Mustache. The best we can do is propagate the full hash through to the child partial.

**Comment by evanmiller** [comment]
Thanks for the explanation. Should I file an issue with Template::Mustache about this? My understanding of partials is that they are to be treated exactly the same as a compile-time text expansion.

As implied by the example I want to use a `link` partial for URL construction that can be overridden by specific layouts. The solution you provide creates a lot more work because it means I need separate partials for every link-containing variable.

**Comment by scmorrison** [comment]
This is more of a trade-off for supporting partial-level variables. The `link` partial has been pre-rendered with its variables before it is included inside the `see_all_pages` loop.

**Comment by evanmiller** [comment]
Do you have any suggestions (or plans) for supporting per-layout URLs? I might be able to hack around it if there are custom layout variables of some kind available, maybe similar to i18n variables. E.g. I would make `layout.root_url`, `layout.separator`, `layout.url_postfix`, etc.

**Comment by scmorrison** [comment]
Yeah, that is a good idea. We could take any variables defined in layout yaml to a `layout` hash. 

layout.mustache
```
---
root_url: ...
separator: ....
url_postfix: ...
misc: ...
---
```

would become `layout.root_url`, `layout.separator`, `layout.url_postfix`, `layout.misc`.

**Comment by evanmiller** [comment]
@scmorrison That works for me. I think with a `layout` hash in place, I'll be able work around the loop-variable issue.

At any rate, the original issue here is resolved, so I will close out this issue.

**Comment by scmorrison** [comment]
The `layout` variable is now available. Please let me know if there are any issues. This variable is accessible even if the page uses the `nolayout` flag.
