### ISSUE TITLE
Variables inside partials are not HTML-encoded

### ISSUE THREAD

**Issue by evanmiller** [scmorrison/uzu#34]
pages/index.mustache:
```
---
title: "The famous <blink> tag"
---
{{> header }}
<h1>{{ title }}</h1>
```

partials/header.mustache:
```
<title>{{ title }}</title>
```

Expected output:
```
<title>The famous &lt;blink&gt; tag</title>
<h1>The famous &lt;blink&gt; tag</h1>
```

Actual output:
```
<title>The famous <blink> tag</title>
<h1>The famous &lt;blink&gt; tag</h1>
```

**Comment by scmorrison** [comment]
@evanmiller, this should be working correctly now, but you will need to make a small modification to your layout template. You need to include `content` as a partial instead of as a variable.

This:
```
{{ content }}
```

is now:
```
{{> content }}
```

This update should resolve any html-decode issues you were having as well.

**Comment by evanmiller** [comment]
Thanks, it works as expected now.
