### ISSUE TITLE
Support partial variables

### ISSUE THREAD

**Issue by evanmiller** [scmorrison/uzu#4]
Pages can have their own variables; partials cannot. It would be useful to let partials define internal variables at the top of the template, similar to pages. I guess you would need to decide which variable would take precedence in the event of a name conflict.

**Comment by scmorrison** [comment]
I am open to adding this functionality, can you give some example for how this could be useful? I am sure there are many use cases I am not considering.

**Comment by evanmiller** [comment]
I have an index page with a list of articles and a list of software projects. What I'd like to do on the index page is:

```
...layout layout...
[% INCLUDE list_articles %]
...layout layout...
[% INCLUDE list_software %]
...layout layout...
```

Within the `list_articles` partial, I'd like to define the articles as variables up top, with attributes `name`, `url`, `new`, etc. Basically I am using partials as a way to refactor large pages into manageable chunks that are not necessarily re-used across pages.

**Comment by scmorrison** [comment]
Ok, that makes sense. Would you be able to use i18n variables for now?

```
list_articles:
    - article....
    - article....
list_software:
    - software....
    - software....
```

...and then only reference them in the partial files.

```yaml
[% for article in i18n.list_articles %]
...
```

**Comment by scmorrison** [comment]
Hi @evanmiller,

I have added initial support for local variables in partial templates. Partial variables will override page variables. 

Thanks,
Sam

**Comment by evanmiller** [comment]
Thanks!
