### ISSUE TITLE
The number 0 is not rendered

### ISSUE THREAD

**Issue by evanmiller** [scmorrison/uzu#40]
```
---
annual: 0
---
${{ annual }}
```
Expected: $0
Actual: $

**Comment by scmorrison** [comment]
Thanks @evanmiller, I'll take a look. Just in case you need the zero right away you can use:

```
---
annual: "0"
---

**Comment by scmorrison** [comment]
Hi @evanmiller,

This only affects mustache templates. I have opened a new [Issue](https://github.com/softmoth/p6-Template-Mustache/issues/25) on Template::Mustache. 

For now please use the string `'0'` for zeros if you need these in your templates. Again, thanks for posting the issue. I will keep this issue open until I hear anything from Template::Mustache.

**Comment by scmorrison** [comment]
@evanmiller, this issue has been resolved in the `Template::Mustache` (https://github.com/softmoth/p6-Template-Mustache/issues/25). Please upgrade your local `Template::Mustache`, you will probably need to clear out the old `Template::Mustache` first:

```
zef uninstall Template::Mustache
rm -rf ~/.zef/store/p6-Template-Mustache.git
rm -rf ~/.zef/tmp/p6-Template-Mustache.git
```
Then reinstall:

`zef install Template::Mustache`

Thanks again,
Sam

**Comment by evanmiller** [comment]
Thanks, works great now.
