### ISSUE TITLE
Add OSX to Travis build targets

### ISSUE THREAD

**Issue by evanmiller** [scmorrison/uzu#42]
I seem to hit errors often when upgrading Uzu on OS X. It would be nice to have a Travis build target so that I can rule out platform issues.

**Comment by scmorrison** [comment]
Hi @evanmiller, this is definately a goal. Right now Perl 6 builds are not available on the macOS environment on travis, but I will add an osx build target as soon as it becomes available. 

Going to close this issue for now. Thanks again.
