### ISSUE TITLE
Uzu theme and demo site

### ISSUE THREAD

**Issue by uzluisf** [scmorrison/uzu#44]
When I came across Uzu, I was happy to learn there was a static site generator written in Perl 6. However, the fact that I couldn't figure out how to create themes and write Mustache templates kept me from trying it out. I know there's the simple site created with `uzu init` but I always wished it had more content (Mustache templates and partials, CSS and more HTML pages).

I finally got around it and created a demo website with a more polished theme. The site is live at https://uzluisf.github.io/uzu-demo-site/ and its repo is located at https://github.com/uzluisf/uzu-demo-site. If you wish, you can provide it as Uzu's default theme. Else, I think it'd be great to have a repo for Uzu themes.

**Comment by scmorrison** [comment]
Hi @uzluisf, thanks for creating this. I will add a link to `uzu-demo-site` to the readme under `Getting Started`.

**Comment by uzluisf** [comment]
No problem ;-)!

**Comment by scmorrison** [comment]
@uzluisf I have added a link to the Uzu Demo Site to the readme. Thanks again!
