### ISSUE TITLE
Generating files with non-html extensions

### ISSUE THREAD

**Issue by evanmiller** [scmorrison/uzu#7]
I'd like to use Uzu to generate an RSS feed (a file with extension `xml` in my case). I didn't see a way to do this in the documentation.

**Comment by scmorrison** [comment]
This should work now. If a template has an extension before the template extension then uzu will use that extension, otherwise it will use html.

`somefile.xml.mustache` should become `somefile.xml`

This is only for page templates.

Thanks,
Sam

**Comment by evanmiller** [comment]
Thanks!
